export const medications = [
  "Amoxicillin",
  "Atorvastatin",
  "Azithromycin",
  "Buscopan",
  "Cefalexine Syrup",
  "Cefixime",
  "Clindamycin",
  "Dicycloverine",
  "Feboxostat",
  "Ketoconazole",
  "Losartan",
  "Mefenamic Acid",
  "Montelukast + Levocetirizine",
  "Omeprazole",
  "Paracetamol",
  "Propylthiouracil",
  "Rosuvastatin + Ezetimibe",
  "Sitagliptin",
  "Stugeron",
  "Tamsulosin",
];
